# Label rules based on file changes

bug:
  - changed-files:
      - any-glob-to-any-file: ['src/**', 'tests/**']

feature:
  - changed-files:
      - any-glob-to-any-file: ['src/**']

documentation:
  - changed-files:
      - any-glob-to-any-file: ['docs/**', '**/*.md']

priority:high:
  - changed-files:
      - any-glob-to-any-file: ['src/security/**']
